development:
  adapter: postgresql
  database: cau_database
  host: localhost
  username:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cau_database
  host: localhost
  username: 
  pool: 5
  timeout: 5000
